[application]
name = "aio-idea"
title = "AIO IDEA"

[[plugins]]
git = "https://github.com/org-aio/aio-plugin-platform-links.git"
rev = "8be1263cd6a5e366fbe8ff2bf5a1f95580ccaa0a"

[[plugins]]
git = "https://github.com/org-aio/aio-plugin-space.git"
rev = "4b37ce8654ceeccb6885dfd8724e9b7801fa649b"
